name: First Workflow GitHub Actions GO

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main, developer ]
  pull_request:
    branches: [ main, developer ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:	
    name: Runnig the Job test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Check Out
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: 'maxcedro'
          password: ${{ secrets.DOCKERHUB_PASSWORD }}       

      - name: Build and Push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          tags: 'maxcedro/contactsconsult:latest'
          push: true

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore

      - name: Unit and Integration Tests 
        run: dotnet test --no-build --verbosity normal         
